### ISSUE TITLE
Unauthorized Exception

### ISSUE THREAD

**Issue by neok0** [SammyTheBEAST/DarkFeed_Connector#2]
After a short period of time (~within 24h) the script suddently stops working due to an HTTP Error exception
`401 Client Error: Unauthorized for url`

It seems the cookie gets invalid at some point, once I renew the cookie value the script starts working again. According to the website this cookie should be valid for 20 days which I cannot confirm. 

Is this a known issue?

**Comment by Ian-Costa18** [comment]
Yes, this is an issue with how the cookies work server side, the cookies may sometimes reset which we do not have control over. In my opinion, this would be better done with an API key but that is not how DarkFeed works at the moment.

**Comment by Ian-Costa18** [comment]
I have heard there is a plan to switch from cookies to an API key system, so this should not be a problem for much longer.
